# OCP Cost Management Collector Setup
---

- name: Run the Setup or Add Cluster
  hosts: admin.na.shared.opentlc.com
  become: true
  roles:
    - {role: 'setup', tags: 'setup'}
    - {role: 'add', tags: 'add'}
